name: Multispace - Apply Terraform

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/multispace-apply.yml
      - terraform/multispace/**
  workflow_dispatch:

jobs:
  call-apply-terraform:
    uses: ./.github/workflows/terraform-apply.yml
    secrets: inherit
    with:
      terraform-folder: multispace
      STATE_KEY: ${{ secrets.TFSTATE_KEY }}
      OCTOPUS_APIKEY: ${{ secrets.OCTOPUS_APIKEY }}
    permissions:
      id-token: write
      contents: read
