name: Team A - Apply Terraform

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/team-a-apply.yml
      - terraform/team-a/**
  workflow_dispatch:

jobs:
  call-apply-terraform:
    uses: ./.github/workflows/terraform-apply.yml
    secrets: inherit
    with:
      terraform-folder: team-a
      STATE_KEY: ${{ secrets.TEAM_A_STATEKEY }}
      OCTOPUS_APIKEY: ${{ secrets.TEAM_A_APIKEY }}
    permissions:
      id-token: write
      contents: read
